/**
 * Created by luowendi on 2017/4/16.
 */
export const CHANGE_CURRENT_THEME_ID = 'CHANGE_CURRENT_THEME_ID'
export const ADD_NEWS = 'ADD_NEWS'
export const ADD_NEWID ='ADD_NEWID'
export const STORY_EXTRA = 'STORY_EXTRA'
export const CHANGE_FIRST_LOAD = 'CHANGE_FIRST_LOAD'
export const CHANGE_FIRST_SIDEBAR ='CHANGE_FIRST_SIDEBAR'
export const DELETE_STORIES = 'DELETE_STORIES'
export const DELETE_IDS = 'DELETE_IDS'
export const JUDGE_COLLECT_STATE = 'JUDGE_COLLECT_STATE'
export const CHANGE_COLLECT_STATE = 'CHANGE_COLLECT_STATE'
export const CHANGE_GO_TYPES = 'CHANGE_GO_TYPES'
export const ADD_THEME = 'ADD_THEME'
export const ADD_EDITOR_ID = 'ADD_EDITOR_ID'
export const ADD_ALL_NEWS = 'ADD_ALL_NEWS'
export const ADD_NEXT_ID = 'ADD_NEXT_ID'
export const CHANGE_MODEL = 'CHANGE_MODEL'
